### ISSUE TITLE
Post Alignment Visualization

### ISSUE THREAD

**Issue by nickhir** [griffithlab/pmbio.org#23]
Hey, 
First of all I want to say how grateful and thankful I am for the comprehensive workshop!
It really helps a lot to work with genomics data from start to finish!

With that being said, I have no idea if the workshop still gets updated, but I just wanted to say, that it might be helpful to mention, that we should load hg38 for the Post Alignment Visualization. By defaul IGV loads hg19, but we aligned to hg38, so there will be alot of mismatches.

Again, thank you very much for the workshop.

Cheers!

**Comment by malachig** [comment]
Thanks!

Yeah this is a general feature of IGV.  It usually remembers what the user last did.  So the first time it might be hg19.  But for various people using this workshop it could be something else as well.

I have added some reminders about this in the workshop.  Should go live in a few minutes.
