### ISSUE TITLE
Simplify VEP installation

### ISSUE THREAD

**Issue by zlskidmore** [griffithlab/pmbio.org#5]
Currently we install VEP 93.5 however this requires installing an older version of perl (5.22) than the system version on ubuntu 18.04 (perl 5.26). The new version of VEP 94.5 works with perl 5.26 so this section can be drastically simplified

**Comment by jeszyman** [comment]
I changed the directions to install VEP 94, and perl 5.26 is no longer needed.

**Comment by malachig** [comment]
Awesome!
